#!/bin/sh
export PATH="/bin"

mount -t devtmpfs devtmpfs /dev

# Mount Linux FS
mount -t ext4 /dev/system /mnt
mount -t squashfs -o loop /mnt/usr.sqsh /mnt/usr

# Move and mount proc and sys and such
umount /dev

mount -t proc proc /mnt/proc
mount -t sysfs sysfs /mnt/sys

mount -t devtmpfs devtmps /mnt/dev
mkdir -p /mnt/dev/pts /mnt/dev/shm

mount -t devpts devpts /mnt/dev/pts
mount -t tmpfs tmpfs /mnt/dev/shm

# Change roots
exec switch_root /mnt /lib/systemd/systemd

